# Makefile for HW1: ArrayList
# Matt Russell
# 
# This Makefile will build unit_test for the unit_testing 
# framework.

CXX=clang++
CXXFLAGS=-g3 -Wall -Wextra -Wpedantic -Wshadow


HOHLS: HOHLS.cpp
	${CXX} ${CXXFLAGS} -o HOHLS HOHLS.cpp

clean: 
	rm *.o a.out *~ *#
